---
- name: setting some facts for using as part of conditions and configurations
  set_fact:
    usable_max_memory: "{{ ansible_memtotal_mb * 0.85 }}"

- name: turning on overcommit by sysctl
  sysctl:
    name: vm.overcommit_memory
    value: '1'

- name: setting ipv4 tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: '409600'

- name: "increasing somaxconn on the host to {{ sysctl.somaxconn }}"
  sysctl:
    name: net.core.somaxconn
    value: "{{ sysctl.somaxconn }}"

- name: disabling transparent huge pages on server by changing grub configuration
  lineinfile:
    dest: /etc/default/grub
    state: present
    line: 'GRUB_CMDLINE_LINUX="transparent_hugepage=never $GRUB_CMDLINE_LINUX"'
  register: grub

- name: rebuilding grub config file
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub.changed

- name: installing necessary packages
  apt:
    name: redis
    state: latest
    update_cache: yes
    force: yes
    force_apt_get: yes

- name: restarting system for affecting changes on grub
  reboot:
    reboot_timeout: 300
  when: grub.changed

- name: adding redis group
  group:
    name: redis
    state: present

- name: adding redis system user
  user:
    name: redis
    create_home: no
    group: redis
    shell: /bin/false
    system: yes

- name: creating necessary directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: redis
    group: redis
  with_items:
    - /etc/redis
    - /var/log/redis
    - "/var/lib/redis/{{ server.port }}"

- name: creating configuration for redis server service
  template:
    src: redis-server.conf.j2
    dest: "/etc/redis/{{ server.port }}.conf"
    mode: '0644'
    owner: redis
    group: redis
  register: config

- name: creating systemd service unit for redis server service
  template:
    src: redis-server.service.j2
    dest: /lib/systemd/system/redis-server.service
    mode: '0644'
    owner: root
    group: root
  register: unit

- name: affecting new systemd service changes by reloading the daemon
  systemd:
    name: redis-server
    enabled: yes
    daemon-reload: yes
    state: restarted
  when: unit.changed or config.changed

- name: adding logrotate config file
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/redis
    owner: root
    group: root
    mode: '0644'
