---
- name: setting some facts for using as part of conditions and configurations
  set_fact:
    usable_max_memory: "{{ ansible_memtotal_mb * 0.85 }}"

- name: turning on overcommit by sysctl
  sysctl:
    name: vm.overcommit_memory
    value: '1'

- name: setting ipv4 tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: '409600'

- name: "increasing somaxconn on the host to {{ redis_sysctl.somaxconn }}"
  sysctl:
    name: net.core.somaxconn
    value: "{{ redis_sysctl.somaxconn }}"

- name: disabling transparent huge pages on server by changing grub configuration
  lineinfile:
    dest: /etc/default/grub
    state: present
    line: 'GRUB_CMDLINE_LINUX="transparent_hugepage=never $GRUB_CMDLINE_LINUX"'
  register: grub

- name: rebuilding grub config file
  command: grub-mkconfig -o /boot/grub/grub.cfg
  when: grub.changed

- name: restarting system for affecting changes on grub
  reboot:
    reboot_timeout: 300
  when: grub.changed

- name: add gpg key to apt keys
  apt_key:
    url: https://packages.redis.io/gpg
    state: present

- name: add redis repository to sources list
  apt_repository:
    repo: deb https://packages.redis.io/deb bullseye main
    filename: redis.list
    state: present

- name: install redis
  apt:
    name: redis
    force_apt_get: yes
    update_cache: yes

- name: create necessary directories
  file:
    path: /var/lib/redis/6379
    state: directory
    owner: redis
    group: redis

- name: configure redis
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0640'
  notify: restart redis service
